import type { Metadata } from 'next'
import { Fraunces, IBM_Plex_Mono, Work_Sans } from 'next/font/google'
import { cookies } from 'next/headers'
import './globals.css'

export const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-fraunces',
  weight: ['500', '600'],
})

export const workSans = Work_Sans({
  subsets: ['latin'],
  variable: '--font-work-sans',
  weight: ['400', '500'],
})

export const plexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  variable: '--font-plex-mono',
  weight: ['400', '500'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: LayoutProps<'/'>) {
  const cookieStore = await cookies()
  const dark = cookieStore.get('theme')?.value === 'dark'

  return (
    <html
      lang='en'
      className={`${fraunces.variable} ${workSans.variable} ${plexMono.variable} h-full antialiased ${dark ? 'dark' : ''}`}
    >
      <body className='min-h-full'>
        <main>{children}</main>
      </body>
    </html>
  )
}
